@startuml

actor DA as "Data Analyst"

rectangle Database

rectangle "World Population Data System" {
    usecase UC1 as "Get The top N populated capital cities in a continent "

    usecase UCa as "Print countries  "

    DA - UC1
    UC1 ..> UCa : include
    UC1 - Database
}
@enduml