@startuml

actor DA as "Data Analyst"

rectangle Database

rectangle "World Population Data System" {
    usecase UC1 as "All the capital cities in a region organised by largest population to smallest.
"

    usecase UCa as "Print Cities  Data "

    DA - UC1
    UC1 ..> UCa : include
    UC1 - Database
}
@enduml